[run]
init_cmds = [
	["go", "run", "./main.go"],
]
watch_all = true
follow_symlinks = true
watch_dirs = [
	"$WORKDIR/pkg",
	"$WORKDIR/public",		# Directories to watch
]
watch_exts = [".go", ".ini", ".toml", ".template.html"]
build_delay = 1500
cmds = [
  ["go", "run", "main.go"]
]